# Generated by Django 5.2.7 on 2025-11-10 08:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningCX',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cx_name', models.CharField(max_length=200)),
                ('cx_data', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cxs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CX Preference',
                'verbose_name_plural': 'CX Preferences',
                'db_table': 'prunplanner_planning_cxs',
            },
        ),
        migrations.CreateModel(
            name='PlanningEmpire',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('empire_name', models.CharField(max_length=200)),
                ('empire_faction', models.CharField(choices=[('NONE', 'None'), ('ANTARES', 'Antares'), ('BENTEN', 'Benten'), ('HORTUS', 'Hortus'), ('MORIA', 'Moria'), ('OUTSIDEREGION', 'Outsideregion')], max_length=20)),
                ('empire_permits_used', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('empire_permits_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('cx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxs', to='planning.planningcx')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empire',
                'verbose_name_plural': 'Empires',
                'db_table': 'prunplanner_planning_empires',
            },
        ),
        migrations.CreateModel(
            name='PlanningPlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(max_length=200)),
                ('planet_natural_id', models.CharField(db_index=True, max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('plan_permits_used', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('plan_cogc', models.CharField(choices=[('---', 'None'), ('AGRICULTURE', 'Agriculture'), ('CHEMISTRY', 'Chemistry'), ('CONSTRUCTION', 'Construction'), ('ELECTRONICS', 'Electronics'), ('FOOD_INDUSTRIES', 'Food Industries'), ('FUEL_REFINING', 'Fuel Refining'), ('MANUFACTURING', 'Manufacturing'), ('METALLURGY', 'Metallurgy'), ('RESOURCE_EXTRACTION', 'Resource Extraction'), ('PIONEERS', 'Pioneers'), ('SETTLERS', 'Settlers'), ('TECHNICIANS', 'Technicians'), ('ENGINEERS', 'Engineers'), ('SCIENTISTS', 'Scientists')], max_length=20)),
                ('plan_corphq', models.BooleanField(default=False)),
                ('plan_data', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'prunplanner_planning_plans',
            },
        ),
        migrations.CreateModel(
            name='PlanningEmpirePlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empire_plans', to='planning.planningempire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empire_plan_links', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_empires', to='planning.planningplan')),
            ],
            options={
                'verbose_name': 'Empire-Plan Link',
                'verbose_name_plural': 'Empire-Plan Links',
                'db_table': 'prunplanner_planning_jct_empire_plan',
                'unique_together': {('empire', 'plan')},
            },
        ),
        migrations.AddField(
            model_name='planningempire',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='empires', through='planning.PlanningEmpirePlan', to='planning.planningplan'),
        ),
    ]
