# Generated by Django 5.2.7 on 2026-01-23 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='planningempireplan',
            index=models.Index(fields=['plan', 'empire'], name='jct_plan_empire_idx'),
        ),
        migrations.AddIndex(
            model_name='planningempireplan',
            index=models.Index(fields=['user'], name='idx_jct_user_lookup'),
        ),
    ]
