# Generated by Django 5.2.10 on 2026-02-02 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planningempireplan_jct_plan_empire_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningShared',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='planning.planningplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Share',
                'verbose_name_plural': 'Plan Shares',
                'db_table': 'prunplanner_planning_shares',
            },
        ),
    ]
