# Generated by Django 5.2.10 on 2026-02-02 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planningshared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planningshared',
            constraint=models.UniqueConstraint(fields=('user', 'plan'), name='unique_user_plan_share'),
        ),
    ]
