# Generated by Django 5.2.11 on 2026-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_planningshared_unique_user_plan_share'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningshared',
            options={'verbose_name': 'Shared Plan', 'verbose_name_plural': 'Shared Plans'},
        ),
    ]
