# Generated by Django 5.2.12 on 2026-03-12 09:03

from django.db import migrations, models
from django.contrib.postgres.indexes import GinIndex, OpClass
from django.db.models import F

def backfill_empty_dict(apps, schema_editor):
    PlanningEmpire = apps.get_model('planning', 'PlanningEmpire')
    PlanningEmpire.objects.filter(empire_state__isnull=True).update(empire_state={})

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_planningshared_options'),
    ]

    operations = [
        # nullable first, so it doesnt crash on existing data
        migrations.AddField(
            model_name='planningempire',
            name='empire_state',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RunPython(backfill_empty_dict, reverse_code=reverse_backfill),
        migrations.AlterField(
            model_name='planningempire',
            name='empire_state',
            field=models.JSONField(blank=True, default=dict)
        )
    ]

    # We only append these SQL operations if we are NOT on SQLite
    from django.db import connection
    if not connection.vendor == 'sqlite':
        operations += [
            migrations.RunSQL(
                sql='CREATE INDEX idx_gin_empire_total ON prunplanner_planning_empires USING gin (((empire_state -> \'empire_total\')) jsonb_path_ops);',
                reverse_sql='DROP INDEX IF EXISTS idx_gin_empire_total;',
            ),
            migrations.RunSQL(
                sql='CREATE INDEX idx_gin_plan_details ON prunplanner_planning_empires USING gin ((empire_state -> \'plan_details\'));',
                reverse_sql='DROP INDEX IF EXISTS idx_gin_plan_details;',
            ),
        ]
