# Generated by Django 6.0.4 on 2026-04-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_planningempire_empire_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningempire',
            name='needs_state_sync',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
