# Generated by Django 6.0.8 on 2026-10-03 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_planningempire_needs_state_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningempire',
            name='config_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
