# Generated by Django 6.0.8 on 2026-10-03 08:22

from django.db import migrations
from django.db.models import F


def backfill(apps, schema_editor):
    """Existing empires: last configuration change unknown, start from the last change of any kind."""
    PlanningEmpire = apps.get_model('planning', 'PlanningEmpire')
    PlanningEmpire.objects.update(config_modified_at=F('modified_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_planningempire_config_modified_at'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_code=migrations.RunPython.noop),
    ]
