# Generated by Django 5.2.7 on 2026-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
