# Generated by Django 5.2.7 on 2026-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'Verification Code', 'verbose_name_plural': 'Verification Codes'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
