# Generated by Django 5.2.7 on 2026-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userpreference_delete_dynamicprofilefield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Preference', 'verbose_name_plural': 'Preferences'},
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
