# Generated by Django 5.2.10 on 2026-02-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={'ordering': ('-created',), 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
    ]
