# Generated by Django 5.2.11 on 2026-02-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userapikey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
