# Generated by Django 5.2.12 on 2026-04-07 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfigWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender', models.CharField(choices=[('FIO API', 'Fioapi')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('total_calls', models.PositiveBigIntegerField(default=0)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Config Webhook',
                'verbose_name_plural': 'Config Webhooks',
                'db_table': 'prunplanner_config_webhooks',
            },
        ),
    ]
