# Generated by Django 6.0.8 on 2026-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_globalconfigwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
