# Generated by Django 5.2.7 on 2026-01-21 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('users_active_today', models.PositiveIntegerField(default=0)),
                ('users_active_30d', models.PositiveIntegerField(default=0)),
                ('plan_count', models.PositiveIntegerField(default=0)),
                ('empire_count', models.PositiveIntegerField(default=0)),
                ('cx_count', models.PositiveIntegerField(default=0)),
                ('plan_empire_junctions_count', models.PositiveIntegerField(default=0)),
                ('building_count', models.PositiveIntegerField(default=0)),
                ('building_cost_count', models.PositiveIntegerField(default=0)),
                ('exchange_analytics_count', models.PositiveIntegerField(default=0)),
                ('exchange_cxpc_count', models.PositiveIntegerField(default=0)),
                ('planet_count', models.PositiveIntegerField(default=0)),
                ('planet_cogc_count', models.PositiveIntegerField(default=0)),
                ('planet_productionfee_count', models.PositiveIntegerField(default=0)),
                ('planet_resource_count', models.PositiveIntegerField(default=0)),
                ('recipe_count', models.PositiveIntegerField(default=0)),
                ('recipe_input_count', models.PositiveIntegerField(default=0)),
                ('recipe_output_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Statistic',
                'verbose_name_plural': 'App Statistics',
                'db_table': 'prunplanner_statistics_app',
            },
        ),
    ]
