# Generated by Django 5.2.7 on 2026-01-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatistic',
            name='material_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
