# Generated by Django 5.2.10 on 2026-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_appstatistic_material_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatistic',
            name='cx_count_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatistic',
            name='empire_count_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatistic',
            name='plan_count_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstatistic',
            name='user_count_delta',
            field=models.IntegerField(default=0),
        ),
    ]
