# Generated by Django 6.0.4 on 2026-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_appstatistic_cx_count_delta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPlanAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_natural_id', models.CharField(db_index=True, max_length=7, unique=True)),
                ('total_plans_analyzed', models.PositiveIntegerField(default=0)),
                ('insights_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Aggregate',
                'verbose_name_plural': 'Plan Aggregates',
                'db_table': 'prunplanner_statistics_plan_aggregate',
                'ordering': ['-last_updated'],
            },
        ),
    ]
