# Generated by Django 6.0.4 on 2026-04-16 12:41

import django.db.models.deletion
from django.db import migrations, models

def apply_postgres_tuning(apps, schema_editor):
    # Only execute if we are on a PostgreSQL backend
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE prunplanner_statistics_empire_material_snapshot SET (fillfactor = 80);")
        cursor.execute("""
            ALTER TABLE prunplanner_statistics_empire_material_snapshot SET (
                autovacuum_vacuum_scale_factor = 0.05,
                autovacuum_vacuum_threshold = 50
            );
        """)

def reverse_postgres_tuning(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE prunplanner_statistics_empire_material_snapshot RESET (fillfactor);")
        cursor.execute("""
            ALTER TABLE prunplanner_statistics_empire_material_snapshot RESET (
                autovacuum_vacuum_scale_factor,
                autovacuum_vacuum_threshold
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticsplanaggregate'),
        ('planning', '0006_planningempire_empire_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEmpireMaterialSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_ticker', models.CharField(db_index=True, max_length=3)),
                ('production', models.FloatField(default=0.0)),
                ('consumption', models.FloatField(default=0.0)),
                ('delta', models.FloatField(default=0.0)),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_snapshot', to='planning.planningempire')),
            ],
            options={
                'verbose_name': 'Empire Material Snapshot',
                'verbose_name_plural': 'Empire Material Snapshots',
                'db_table': 'prunplanner_statistics_empire_material_snapshot',
                'indexes': [models.Index(fields=['material_ticker', 'delta'], name='prunplanner_materia_62060a_idx')],
                'unique_together': {('empire', 'material_ticker')},
            },
        ),
        migrations.RunPython(apply_postgres_tuning, reverse_postgres_tuning),
    ]
