# Generated by Django 6.0.4 on 2026-04-17 06:51

from django.db import migrations, models
from decimal import Decimal, ROUND_HALF_UP

def clean_and_recalculate_precision(apps, schema_editor):
    Snapshot = apps.get_model('analytics', 'AnalyticsEmpireMaterialSnapshot')

    batch_size = 1000
    queryset = Snapshot.objects.all()
    to_update = []

    for obj in Snapshot.objects.iterator(chunk_size=batch_size):
        # Round to 6 decimal places to kill float noise
        p = Decimal(str(obj.production)).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
        c = Decimal(str(obj.consumption)).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)

        obj.production = p
        obj.consumption = c
        obj.delta = p - c

        to_update.append(obj)

        # When batch is full, perform one large update
        if len(to_update) >= batch_size:
            Snapshot.objects.bulk_update(to_update, ['production', 'consumption', 'delta'])
            to_update = []

    if to_update:
        Snapshot.objects.bulk_update(to_update, ['production', 'consumption', 'delta'])

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('analytics', '0005_analyticsempirematerialsnapshot'),
        ('planning', '0006_planningempire_empire_state'),
    ]

    operations = [
        # structure
        migrations.AlterField(
            model_name='analyticsempirematerialsnapshot',
            name='consumption',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analyticsempirematerialsnapshot',
            name='delta',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analyticsempirematerialsnapshot',
            name='production',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),

        # data cleanup
        migrations.RunPython(clean_and_recalculate_precision, reverse_code=migrations.RunPython.noop),

        # clean indexes and constraints
        migrations.RenameIndex(
            model_name='analyticsempirematerialsnapshot',
            new_name='idx_material_ticker_delta',
            old_name='prunplanner_materia_62060a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='analyticsempirematerialsnapshot',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='analyticsempirematerialsnapshot',
            index=models.Index(fields=['empire', 'delta'], name='idx_empire_delta'),
        ),
        migrations.AddConstraint(
            model_name='analyticsempirematerialsnapshot',
            constraint=models.UniqueConstraint(fields=('empire', 'material_ticker'), name='unique_empire_material_ticker'),
        ),
    ]
