# Generated by Django 6.0.8 on 2026-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_rename_prunplanner_materia_62060a_idx_idx_material_ticker_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatistic',
            name='signups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appstatistic',
            name='users_active_7d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
