# Generated by Django 6.0.8 on 2026-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_appstatistic_signups_appstatistic_users_active_7d'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsplanaggregate',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
