habitations: dict[str, dict[str, int]] = {
    'HBB': {
        'pioneers': 75,
        'settlers': 75,
        'technicians': 0,
        'engineers': 0,
        'scientists': 0,
        'area': 14,
    },
    'HBC': {
        'pioneers': 0,
        'settlers': 75,
        'technicians': 75,
        'engineers': 0,
        'scientists': 0,
        'area': 17,
    },
    'HBM': {
        'pioneers': 0,
        'settlers': 0,
        'technicians': 75,
        'engineers': 75,
        'scientists': 0,
        'area': 20,
    },
    'HBL': {
        'pioneers': 0,
        'settlers': 0,
        'technicians': 0,
        'engineers': 75,
        'scientists': 75,
        'area': 22,
    },
    'HB1': {
        'pioneers': 100,
        'settlers': 0,
        'technicians': 0,
        'engineers': 0,
        'scientists': 0,
        'area': 10,
    },
    'HB2': {
        'pioneers': 0,
        'settlers': 100,
        'technicians': 0,
        'engineers': 0,
        'scientists': 0,
        'area': 12,
    },
    'HB3': {
        'pioneers': 0,
        'settlers': 0,
        'technicians': 100,
        'engineers': 0,
        'scientists': 0,
        'area': 14,
    },
    'HB4': {
        'pioneers': 0,
        'settlers': 0,
        'technicians': 0,
        'engineers': 100,
        'scientists': 0,
        'area': 16,
    },
    'HB5': {
        'pioneers': 0,
        'settlers': 0,
        'technicians': 0,
        'engineers': 0,
        'scientists': 100,
        'area': 18,
    },
}
