# Generated by Django 5.2.7 on 2025-11-10 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBuilding',
            fields=[
                ('building_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('building_ticker', models.CharField(db_index=True, max_length=3)),
                ('expertise', models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('CHEMISTRY', 'Chemistry'), ('CONSTRUCTION', 'Construction'), ('ELECTRONICS', 'Electronics'), ('FOOD_INDUSTRIES', 'Food Industries'), ('MANUFACTURING', 'Manufacturing'), ('METALLURGY', 'Metallurgy'), ('RESOURCE_EXTRACTION', 'Resource Extraction'), ('FUEL_REFINING', 'Fuel Refining')], db_index=True, max_length=50, null=True)),
                ('pioneers', models.PositiveIntegerField()),
                ('settlers', models.PositiveIntegerField()),
                ('technicians', models.PositiveIntegerField()),
                ('engineers', models.PositiveIntegerField()),
                ('scientists', models.PositiveIntegerField()),
                ('area_cost', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'prunplanner_game_buildings',
            },
        ),
        migrations.CreateModel(
            name='GameExchange',
            fields=[
                ('ticker_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)])),
                ('ticker', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(1)])),
                ('exchange_code', models.CharField(choices=[('AI1', 'Ai1'), ('CI1', 'Ci1'), ('CI2', 'Ci2'), ('IC1', 'Ic1'), ('NC1', 'Nc1'), ('NC2', 'Nc2')], db_index=True, max_length=3)),
                ('mm_buy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mm_sell', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_average', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ask', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bid', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ask_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bid_count', models.PositiveIntegerField(blank=True, null=True)),
                ('supply', models.PositiveIntegerField(blank=True, null=True)),
                ('demand', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'db_table': 'prunplanner_game_exchanges',
            },
        ),
        migrations.CreateModel(
            name='GameMaterial',
            fields=[
                ('material_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(db_index=True, max_length=3)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'prunplanner_game_materials',
            },
        ),
        migrations.CreateModel(
            name='GamePlanet',
            fields=[
                ('automation_last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('automation_refresh_status', models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('automation_error', models.TextField(blank=True, null=True)),
                ('automation_next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('planet_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('planet_natural_id', models.CharField(db_index=True)),
                ('planet_name', models.CharField(blank=True, null=True)),
                ('system_id', models.CharField(db_index=True, max_length=32)),
                ('magnetic_field', models.FloatField()),
                ('mass', models.FloatField()),
                ('mass_earth', models.FloatField()),
                ('orbit_semimajor_axis', models.FloatField()),
                ('orbit_eccentricity', models.FloatField()),
                ('orbit_inclination', models.FloatField()),
                ('orbit_right_ascension', models.FloatField()),
                ('orbit_periapsis', models.FloatField()),
                ('orbit_index', models.IntegerField()),
                ('radiation', models.FloatField()),
                ('radius', models.FloatField()),
                ('sunlight', models.FloatField()),
                ('surface', models.BooleanField(db_index=True)),
                ('gravity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('fertility', models.FloatField()),
                ('gravity_type', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=10)),
                ('pressure_type', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=10)),
                ('temperature_type', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=10)),
                ('fertility_type', models.BooleanField(db_index=True, default=False)),
                ('has_localmarket', models.BooleanField(db_index=True)),
                ('has_chamberofcommerce', models.BooleanField(db_index=True)),
                ('has_warehouse', models.BooleanField(db_index=True)),
                ('has_administrationcenter', models.BooleanField(db_index=True)),
                ('has_shipyard', models.BooleanField(db_index=True)),
                ('faction_code', models.CharField(blank=True, choices=[('NC', 'Nc'), ('CI', 'Ci'), ('AI', 'Ai'), ('IC', 'Ic')], max_length=2, null=True)),
                ('faction_name', models.CharField(blank=True, choices=[('NEO Charter Exploration', 'Neo Charter Exploration'), ('Castillo-Ito Mercantile', 'Castillo Ito Mercantile'), ('Antares Initiative', 'Antares Initiative'), ('Insitor Cooperative', 'Insitor Cooperative')], max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, choices=[('NCC', 'Ncc'), ('CIS', 'Cis'), ('AIC', 'Aic'), ('ICA', 'Ica')], max_length=3, null=True)),
                ('currency_name', models.CharField(blank=True, choices=[('NCE Coupons', 'Nce Coupons'), ('Sol', 'Sol'), ('Martian Coin', 'Martian Coin'), ('Austral', 'Austral')], max_length=50, null=True)),
                ('base_localmarket_fee', models.FloatField()),
                ('localmarket_fee_factor', models.FloatField()),
                ('warehouse_fee', models.FloatField()),
                ('establishment_fee', models.FloatField()),
                ('population_id', models.CharField(db_index=True, max_length=32)),
                ('cogc_program_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PLANNED', 'Planned'), ('ON_STRIKE', 'On Strike')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
                'db_table': 'prunplanner_game_planets',
            },
        ),
        migrations.CreateModel(
            name='GameRecipe',
            fields=[
                ('standard_recipe_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('building_ticker', models.CharField(db_index=True, max_length=3)),
                ('time_ms', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'prunplanner_game_recipes',
            },
        ),
        migrations.CreateModel(
            name='GameBuildingCost',
            fields=[
                ('building_cost_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_ticker', models.CharField(db_index=True, max_length=3)),
                ('material_amount', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='gamedata.gamebuilding')),
            ],
            options={
                'verbose_name': 'Building Cost',
                'verbose_name_plural': 'Building Costs',
                'db_table': 'prunplanner_game_buildings_costs',
            },
        ),
        migrations.CreateModel(
            name='GameFIOSites',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('automation_last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('automation_refresh_status', models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('automation_error', models.TextField(blank=True, null=True)),
                ('automation_next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('site_data', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fio_site', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FIO Site',
                'verbose_name_plural': 'FIO Sites',
                'db_table': 'prunplanner_game_fio_sites',
            },
        ),
        migrations.CreateModel(
            name='GameFIOStorage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('automation_last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('automation_refresh_status', models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('automation_error', models.TextField(blank=True, null=True)),
                ('automation_next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('storage_data', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fio_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FIO Storage',
                'verbose_name_plural': 'FIO Storages',
                'db_table': 'prunplanner_game_fio_storages',
            },
        ),
        migrations.CreateModel(
            name='GamePlanetCOGCProgram',
            fields=[
                ('planet_cogc_program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_type', models.CharField(blank=True, choices=[('ADVERTISING_AGRICULTURE', 'Agriculture'), ('ADVERTISING_CHEMISTRY', 'Chemistry'), ('ADVERTISING_CONSTRUCTION', 'Construction'), ('ADVERTISING_ELECTRONICS', 'Electronics'), ('ADVERTISING_FOOD_INDUSTRIES', 'Food Industries'), ('ADVERTISING_FUEL_REFINING', 'Fuel Refining'), ('ADVERTISING_MANUFACTURING', 'Manufacturing'), ('ADVERTISING_METALLURGY', 'Metallurgy'), ('ADVERTISING_RESOURCE_EXTRACTION', 'Resource Extraction'), ('WORKFORCE_PIONEERS', 'Workforce Pioneers'), ('WORKFORCE_SETTLERS', 'Workforce Settlers'), ('WORKFORCE_TECHNICIANS', 'Workforce Technicians'), ('WORKFORCE_ENGINEERS', 'Workforce Engineers'), ('WORKFORCE_SCIENTISTS', 'Workforce Scientists')], db_index=True, default=None, max_length=50, null=True)),
                ('start_epochms', models.BigIntegerField(db_index=True)),
                ('end_epochms', models.BigIntegerField(db_index=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogc_programs', to='gamedata.gameplanet')),
            ],
            options={
                'verbose_name': 'Planet COGC Program',
                'verbose_name_plural': 'Planet COGC Programs',
                'db_table': 'prunplanner_game_planet_cogc_programs',
            },
        ),
        migrations.CreateModel(
            name='GamePlanetProductionFee',
            fields=[
                ('planet_production_fee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('CHEMISTRY', 'Chemistry'), ('CONSTRUCTION', 'Construction'), ('ELECTRONICS', 'Electronics'), ('FOOD_INDUSTRIES', 'Food Industries'), ('MANUFACTURING', 'Manufacturing'), ('METALLURGY', 'Metallurgy'), ('RESOURCE_EXTRACTION', 'Resource Extraction'), ('FUEL_REFINING', 'Fuel Refining')], max_length=50)),
                ('workforce_level', models.CharField(choices=[('ENGINEER', 'Engineer'), ('TECHNICIAN', 'Technician'), ('SCIENTIST', 'Scientist'), ('SETTLER', 'Settler'), ('PIONEER', 'Pioneer')], max_length=10)),
                ('fee_amount', models.FloatField()),
                ('fee_currency', models.CharField(choices=[('NCC', 'Ncc'), ('CIS', 'Cis'), ('AIC', 'Aic'), ('ICA', 'Ica')], max_length=3)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_fees', to='gamedata.gameplanet')),
            ],
            options={
                'verbose_name': 'Planet Production Fee',
                'verbose_name_plural': 'Planet Production Fees',
                'db_table': 'prunplanner_game_planet_production_fees',
            },
        ),
        migrations.CreateModel(
            name='GamePlanetResource',
            fields=[
                ('planet_resource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_id', models.CharField(db_index=True, max_length=32)),
                ('resource_type', models.CharField(choices=[('GASEOUS', 'Gaseous'), ('LIQUID', 'Liquid'), ('MINERAL', 'Mineral')], max_length=10)),
                ('factor', models.FloatField()),
                ('daily_extraction', models.FloatField(default=0)),
                ('material_ticker', models.CharField(blank=True, db_index=True, default=None, max_length=3, null=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='gamedata.gameplanet')),
            ],
            options={
                'verbose_name': 'Planet Resource',
                'verbose_name_plural': 'Planet Resources',
                'db_table': 'prunplanner_game_planet_resources',
            },
        ),
        migrations.CreateModel(
            name='GameRecipeInput',
            fields=[
                ('recipe_input_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_ticker', models.CharField(db_index=True, max_length=3)),
                ('material_amount', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='gamedata.gamerecipe')),
            ],
            options={
                'verbose_name': 'Recipe Input',
                'verbose_name_plural': 'Recipe Inputs',
                'db_table': 'prunplanner_game_recipes_inputs',
            },
        ),
        migrations.CreateModel(
            name='GameRecipeOutput',
            fields=[
                ('recipe_output_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_ticker', models.CharField(db_index=True, max_length=3)),
                ('material_amount', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='gamedata.gamerecipe')),
            ],
            options={
                'verbose_name': 'Recipe Output',
                'verbose_name_plural': 'Recipe Outputs',
                'db_table': 'prunplanner_game_recipes_outputs',
            },
        ),
    ]
