# Generated by Django 5.2.7 on 2026-01-15 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExchangeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(1)])),
                ('exchange_code', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ask', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('supply', models.IntegerField(blank=True, null=True)),
                ('demand', models.IntegerField(blank=True, null=True)),
                ('cumulative_volume', models.IntegerField()),
                ('delta_volume', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Exchange Snapshot',
                'verbose_name_plural': 'Exchange Snapshots',
                'db_table': 'prunplanner_game_exchange_snapshots',
                'indexes': [models.Index(fields=['ticker', 'exchange_code', '-created_at'], name='prunplanner_ticker_3425f2_idx')],
            },
        ),
    ]
