# Generated by Django 5.2.7 on 2026-01-15 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_gameexchangesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExchangeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(1)])),
                ('exchange_code', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vwap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_volume', models.IntegerField(default=0)),
                ('avg_supply', models.IntegerField(blank=True, null=True)),
                ('avg_demand', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exchange Summary',
                'verbose_name_plural': 'Exchange Summaries',
                'db_table': 'prunplanner_game_exchange_summary',
                'ordering': ['-date', 'ticker'],
                'indexes': [models.Index(fields=['ticker', 'exchange_code', 'date'], name='prunplanner_ticker_a31adb_idx')],
                'unique_together': {('ticker', 'exchange_code', 'date')},
            },
        ),
    ]
