# Generated by Django 5.2.7 on 2026-01-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0003_gameexchangesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameexchangesnapshot',
            name='traded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameexchangesnapshot',
            name='volume_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
