# Generated by Django 5.2.7 on 2026-01-17 12:52

import django.core.validators
from django.db import migrations, models


def create_materialized_view(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return

    schema_editor.execute("""
        CREATE MATERIALIZED VIEW prunplanner_game_exchanges_analytics AS
            WITH base_aggregated AS (
                    SELECT prunplanner_game_exchanges_cxpc.ticker,
                        COALESCE(prunplanner_game_exchanges_cxpc.exchange_code, 'UNIVERSE'::character varying) AS exchange_code,
                        prunplanner_game_exchanges_cxpc.date_epoch,
                        sum(prunplanner_game_exchanges_cxpc.volume) AS volume,
                        sum(prunplanner_game_exchanges_cxpc.traded) AS traded
                    FROM prunplanner_game_exchanges_cxpc
                    GROUP BY GROUPING SETS ((prunplanner_game_exchanges_cxpc.ticker, prunplanner_game_exchanges_cxpc.exchange_code, prunplanner_game_exchanges_cxpc.date_epoch), (prunplanner_game_exchanges_cxpc.ticker, prunplanner_game_exchanges_cxpc.date_epoch))
                    ), windowed_stats AS (
                    SELECT base_aggregated.ticker,
                        base_aggregated.exchange_code,
                        base_aggregated.date_epoch,
                        base_aggregated.volume,
                        base_aggregated.traded,
                        sum(base_aggregated.volume) OVER w7 AS sum_volume_7d,
                        sum(base_aggregated.volume) OVER w30 AS sum_volume_30d,
                        sum(base_aggregated.traded) OVER w7 AS sum_traded_7d,
                        sum(base_aggregated.traded) OVER w30 AS sum_traded_30d,
                        avg(base_aggregated.traded) OVER w7 AS avg_traded_7d,
                        avg(base_aggregated.traded) OVER w30 AS avg_traded_30d
                    FROM base_aggregated
                    WINDOW w7 AS (PARTITION BY base_aggregated.ticker, base_aggregated.exchange_code ORDER BY base_aggregated.date_epoch RANGE BETWEEN 518400000 PRECEDING AND CURRENT ROW), w30 AS (PARTITION BY base_aggregated.ticker, base_aggregated.exchange_code ORDER BY base_aggregated.date_epoch RANGE BETWEEN '2505600000'::bigint PRECEDING AND CURRENT ROW)
                    )
            SELECT row_number() OVER () AS id,
                ticker,
                exchange_code,
                date_epoch,
                to_timestamp((date_epoch / 1000)::double precision)::date AS calendar_date,
                traded AS traded_daily,
                volume / NULLIF(traded, 0::numeric) AS vwap_daily,
                sum_traded_7d,
                avg_traded_7d,
                sum_volume_7d / NULLIF(sum_traded_7d, 0::numeric) AS vwap_7d,
                sum_traded_30d,
                avg_traded_30d,
                sum_volume_30d / NULLIF(sum_traded_30d, 0::numeric) AS vwap_30d
            FROM windowed_stats;

            CREATE UNIQUE INDEX idx_game_analytics_unique ON prunplanner_game_exchanges_analytics (ticker, exchange_code, date_epoch);
            CLUSTER prunplanner_game_exchanges_analytics USING idx_game_analytics_unique;
            """)


def drop_materialized_view(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return
    schema_editor.execute('DROP MATERIALIZED VIEW IF EXISTS prunplanner_game_exchanges_analytics;')


class Migration(migrations.Migration):
    dependencies = [
        ('gamedata', '0004_gameexchangesnapshot_traded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExchangeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('exchange_code', models.CharField(max_length=20)),
                ('date_epoch', models.BigIntegerField()),
                ('calendar_date', models.DateField()),
                ('traded_daily', models.DecimalField(decimal_places=4, max_digits=20)),
                ('vwap_daily', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sum_traded_7d', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_traded_7d', models.DecimalField(decimal_places=4, max_digits=20)),
                ('vwap_7d', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sum_traded_30d', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_traded_30d', models.DecimalField(decimal_places=4, max_digits=20)),
                ('vwap_30d', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'db_table': 'prunplanner_game_exchanges_analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameExchangeCXPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'ticker',
                    models.CharField(
                        db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    'exchange_code',
                    models.CharField(
                        choices=[
                            ('AI1', 'Ai1'),
                            ('CI1', 'Ci1'),
                            ('CI2', 'Ci2'),
                            ('IC1', 'Ic1'),
                            ('NC1', 'Nc1'),
                            ('NC2', 'Nc2'),
                            ('UNIVERSE', 'Universe'),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ('date_epoch', models.BigIntegerField()),
                ('open_p', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_p', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_p', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_p', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20)),
                ('traded', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'verbose_name': 'Exchange CXPC',
                'verbose_name_plural': 'Exchange CXPCs',
                'db_table': 'prunplanner_game_exchanges_cxpc',
                'unique_together': {('ticker', 'exchange_code', 'date_epoch')},
            },
        ),
        migrations.DeleteModel(
            name='GameExchangeSnapshot',
        ),
        migrations.DeleteModel(
            name='GameExchangeSummary',
        ),
        migrations.AlterField(
            model_name='gameexchange',
            name='exchange_code',
            field=models.CharField(
                choices=[
                    ('AI1', 'Ai1'),
                    ('CI1', 'Ci1'),
                    ('CI2', 'Ci2'),
                    ('IC1', 'Ic1'),
                    ('NC1', 'Nc1'),
                    ('NC2', 'Nc2'),
                    ('UNIVERSE', 'Universe'),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
        migrations.RunPython(create_materialized_view, reverse_code=drop_materialized_view),
    ]
