# Generated by Django 5.2.7 on 2026-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0005_gameexchangeanalytics_gameexchangecxpc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameexchangeanalytics',
            options={'managed': False, 'verbose_name': 'Exchange Analytics', 'verbose_name_plural': 'Exchange Analytics'},
        ),
        migrations.AddField(
            model_name='gamefiosites',
            name='automation_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamefiostorage',
            name='automation_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplanet',
            name='automation_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamefiosites',
            name='automation_refresh_status',
            field=models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamefiostorage',
            name='automation_refresh_status',
            field=models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameplanet',
            name='automation_refresh_status',
            field=models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='ok', max_length=20),
        ),
    ]
