# Generated by Django 5.2.7 on 2026-01-23 07:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_alter_gameexchangeanalytics_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamefiostorage',
            name='user',
        ),
        migrations.CreateModel(
            name='GameFIOPlayerData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('automation_last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('automation_refresh_status', models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('automation_error', models.TextField(blank=True, null=True)),
                ('automation_next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('automation_error_count', models.PositiveIntegerField(default=0)),
                ('schema_version', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_data', models.JSONField(default=dict)),
                ('site_data', models.JSONField(default=dict)),
                ('warehouse_data', models.JSONField(default=dict)),
                ('ship_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fio_playerdata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FIO Player Data',
                'verbose_name_plural': 'FIO Player Data',
                'db_table': 'prunplanner_game_fio_playerdata',
            },
        ),
        migrations.DeleteModel(
            name='GameFIOSites',
        ),
        migrations.DeleteModel(
            name='GameFIOStorage',
        ),
    ]
