# Generated by Django 5.2.7 on 2026-01-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0007_remove_gamefiostorage_user_gamefioplayerdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefioplayerdata',
            name='automation_refresh_status',
            field=models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed')], db_index=True, default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameplanet',
            name='automation_refresh_status',
            field=models.CharField(choices=[('ok', 'OK'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('failed', 'Failed')], db_index=True, default='ok', max_length=20),
        ),
    ]
