# Generated by Django 5.2.7 on 2026-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_alter_gamefioplayerdata_automation_refresh_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameexchangecxpc',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='close_p',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='exchange_code',
            field=models.CharField(choices=[('AI1', 'Ai1'), ('CI1', 'Ci1'), ('CI2', 'Ci2'), ('IC1', 'Ic1'), ('NC1', 'Nc1'), ('NC2', 'Nc2'), ('UNIVERSE', 'Universe')], max_length=8),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='high_p',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='High Price'),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='low_p',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Low Price'),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='open_p',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='traded',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Traded Amount'),
        ),
        migrations.AlterField(
            model_name='gameexchangecxpc',
            name='volume',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Price Volume'),
        ),
        migrations.AddIndex(
            model_name='gameexchangecxpc',
            index=models.Index(fields=['ticker', 'exchange_code'], name='idx_ticker_exchange'),
        ),
        migrations.AddConstraint(
            model_name='gameexchangecxpc',
            constraint=models.UniqueConstraint(fields=('ticker', 'exchange_code', 'date_epoch'), name='unique_ticker_exchange_date'),
        ),
    ]
