# Generated by Django 5.2.11 on 2026-02-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0009_alter_gameexchangecxpc_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebuilding',
            name='expertise',
            field=models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('CHEMISTRY', 'Chemistry'), ('CONSTRUCTION', 'Construction'), ('ELECTRONICS', 'Electronics'), ('FOOD_INDUSTRIES', 'Food Industries'), ('MANUFACTURING', 'Manufacturing'), ('METALLURGY', 'Metallurgy'), ('RESOURCE_EXTRACTION', 'Resource Extraction'), ('FUEL_REFINING', 'Fuel Refining')], db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameplanet',
            name='cogc_program_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PLANNED', 'Planned'), ('ON_STRIKE', 'On Strike')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameplanet',
            name='planet_name',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gameplanetresource',
            name='material_ticker',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=3),
        ),
    ]
