# Generated by Django 5.2.11 on 2026-02-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0010_alter_gamebuilding_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebuilding',
            name='expertise',
            field=models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('CHEMISTRY', 'Chemistry'), ('CONSTRUCTION', 'Construction'), ('ELECTRONICS', 'Electronics'), ('FOOD_INDUSTRIES', 'Food Industries'), ('MANUFACTURING', 'Manufacturing'), ('METALLURGY', 'Metallurgy'), ('RESOURCE_EXTRACTION', 'Resource Extraction'), ('FUEL_REFINING', 'Fuel Refining')], db_index=True, default='', max_length=50, null=True),
        ),
    ]
