# Generated by Django 5.2.11 on 2026-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0011_alter_gamebuilding_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplanet',
            name='cogc_program_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PLANNED', 'Planned'), ('ON_STRIKE', 'On Strike')], max_length=10, null=True),
        ),
    ]
