# Generated by Django 5.2.11 on 2026-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0012_alter_gameplanet_cogc_program_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameplanetcogcprogram',
            constraint=models.UniqueConstraint(fields=('planet', 'program_type', 'start_epochms', 'end_epochms'), name='unique_planet_cogc_window'),
        ),
        migrations.AddConstraint(
            model_name='gameplanetproductionfee',
            constraint=models.UniqueConstraint(fields=('planet', 'category', 'workforce_level'), name='unique_planet_fee_category_level'),
        ),
        migrations.AddConstraint(
            model_name='gameplanetresource',
            constraint=models.UniqueConstraint(fields=('planet', 'material_id'), name='unique_planet_material_resource'),
        ),
    ]
