# Generated by Django 5.2.11 on 2026-02-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0013_gameplanetcogcprogram_unique_planet_cogc_window_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlanetInfrastructureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_report_id', models.CharField(db_index=True, max_length=128)),
                ('explorers_grace_enabled', models.BooleanField()),
                ('simulation_period', models.PositiveIntegerField()),
                ('next_population_pioneer', models.IntegerField()),
                ('next_population_settler', models.IntegerField()),
                ('next_population_technician', models.IntegerField()),
                ('next_population_engineer', models.IntegerField()),
                ('next_population_scientist', models.IntegerField()),
                ('population_difference_pioneer', models.IntegerField()),
                ('population_difference_settler', models.IntegerField()),
                ('population_difference_technician', models.IntegerField()),
                ('population_difference_engineer', models.IntegerField()),
                ('population_difference_scientist', models.IntegerField()),
                ('unemployment_rate_pioneer', models.FloatField()),
                ('unemployment_rate_settler', models.FloatField()),
                ('unemployment_rate_technician', models.FloatField()),
                ('unemployment_rate_engineer', models.FloatField()),
                ('unemployment_rate_scientist', models.FloatField()),
                ('open_jobs_pioneer', models.FloatField()),
                ('open_jobs_settler', models.FloatField()),
                ('open_jobs_technician', models.FloatField()),
                ('open_jobs_engineer', models.FloatField()),
                ('open_jobs_scientist', models.FloatField()),
                ('average_happiness_pioneer', models.FloatField()),
                ('average_happiness_settler', models.FloatField()),
                ('average_happiness_technician', models.FloatField()),
                ('average_happiness_engineer', models.FloatField()),
                ('average_happiness_scientist', models.FloatField()),
                ('need_fulfillment_life_support', models.FloatField()),
                ('need_fulfillment_safety', models.FloatField()),
                ('need_fulfillment_health', models.FloatField()),
                ('need_fulfillment_comfort', models.FloatField()),
                ('need_fulfillment_culture', models.FloatField()),
                ('need_fulfillment_education', models.FloatField()),
                ('free_pioneer', models.IntegerField()),
                ('free_settler', models.IntegerField()),
                ('free_technician', models.IntegerField()),
                ('free_engineer', models.IntegerField()),
                ('free_scientist', models.IntegerField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popr_reports', to='gamedata.gameplanet')),
            ],
            options={
                'verbose_name': 'Planet POPR ',
                'verbose_name_plural': 'Planet POPRs',
                'db_table': 'prunplanner_game_planet_popr_reports',
                'ordering': ['-simulation_period'],
                'constraints': [models.UniqueConstraint(fields=('planet', 'simulation_period'), name='unique_planet_popr_simulation_period')],
            },
        ),
    ]
