# Generated by Django 5.2.11 on 2026-02-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0014_gameplanetinfrastructurereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplanetinfrastructurereport',
            options={'ordering': ['-simulation_period'], 'verbose_name': 'Planet POPR', 'verbose_name_plural': 'Planet POPRs'},
        ),
    ]
