# Generated by Django 5.2.11 on 2026-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0015_alter_gameplanetinfrastructurereport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplanetinfrastructurereport',
            name='simulation_period',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
