# Generated by Django 5.2.11 on 2026-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0016_alter_gameplanetinfrastructurereport_simulation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebuilding',
            name='building_type',
            field=models.CharField(choices=[('PLANETARY', 'Planetary'), ('INFRASTRUCTURE', 'Infrastructure'), ('PRODUCTION', 'Production')], default='PRODUCTION', max_length=50),
        ),
    ]
