# Generated by Django 5.2.11 on 2026-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0017_gamebuilding_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplanetresource',
            name='max_daily_extraction',
            field=models.FloatField(default=0),
        ),
    ]
