# Generated by Django 5.2.12 on 2026-03-20 12:54

from django.db import migrations

def update_materialized_view(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return

    schema_editor.execute("DROP MATERIALIZED VIEW IF EXISTS prunplanner_game_exchanges_analytics;")

    schema_editor.execute("""
        CREATE MATERIALIZED VIEW prunplanner_game_exchanges_analytics AS
        WITH constants AS (
         SELECT (EXTRACT(epoch FROM date_trunc('day'::text, now())) * 1000::numeric)::bigint AS today_epoch
        ), physical_exchanges AS (
         SELECT unnest(ARRAY['AI1'::text, 'IC1'::text, 'NC1'::text, 'CI1'::text])::character varying AS exchange_code
        ), ticker_scaffold AS (
         SELECT m.ticker,
            e.exchange_code,
            c.today_epoch AS date_epoch,
            0::numeric AS volume,
            0::numeric AS traded
           FROM prunplanner_game_materials m
             CROSS JOIN physical_exchanges e
             CROSS JOIN constants c
        ), combined_source AS (
         SELECT prunplanner_game_exchanges_cxpc.ticker,
            prunplanner_game_exchanges_cxpc.exchange_code,
            prunplanner_game_exchanges_cxpc.date_epoch,
            prunplanner_game_exchanges_cxpc.volume::numeric AS volume,
            prunplanner_game_exchanges_cxpc.traded::numeric AS traded
           FROM prunplanner_game_exchanges_cxpc
          WHERE prunplanner_game_exchanges_cxpc.date_epoch >= (( SELECT constants.today_epoch - 30::bigint * 86400000
                   FROM constants)) AND exchange_code IN ('AI1', 'IC1', 'NC1', 'CI1')
        UNION ALL
         SELECT ticker_scaffold.ticker,
            ticker_scaffold.exchange_code,
            ticker_scaffold.date_epoch,
            ticker_scaffold.volume,
            ticker_scaffold.traded
           FROM ticker_scaffold
        ), base_aggregated AS (
         SELECT combined_source.ticker,
            COALESCE(combined_source.exchange_code, 'UNIVERSE'::character varying) AS exchange_code,
            combined_source.date_epoch,
            sum(combined_source.volume) AS volume,
            sum(combined_source.traded) AS traded
           FROM combined_source
          GROUP BY GROUPING SETS ((combined_source.ticker, combined_source.exchange_code, combined_source.date_epoch), (combined_source.ticker, combined_source.date_epoch))
        ), windowed_stats AS (
         SELECT base_aggregated.ticker,
            base_aggregated.exchange_code,
            base_aggregated.date_epoch,
            base_aggregated.volume,
            base_aggregated.traded,
            sum(base_aggregated.volume) OVER w7 AS sum_volume_7d,
            sum(base_aggregated.volume) OVER w30 AS sum_volume_30d,
            sum(base_aggregated.traded) OVER w7 AS sum_traded_7d,
            sum(base_aggregated.traded) OVER w30 AS sum_traded_30d,
            avg(base_aggregated.traded) OVER w7 AS avg_traded_7d,
            avg(base_aggregated.traded) OVER w30 AS avg_traded_30d,
                CASE
                    WHEN base_aggregated.traded > 0::numeric THEN base_aggregated.volume / base_aggregated.traded
                    ELSE NULL::numeric
                END AS instant_vwap
           FROM base_aggregated
          WINDOW w7 AS (PARTITION BY base_aggregated.ticker, base_aggregated.exchange_code ORDER BY base_aggregated.date_epoch RANGE BETWEEN 604800000 PRECEDING AND CURRENT ROW), w30 AS (PARTITION BY base_aggregated.ticker, base_aggregated.exchange_code ORDER BY base_aggregated.date_epoch RANGE BETWEEN '2592000000'::bigint PRECEDING AND CURRENT ROW)
        ), locf_logic AS (
         SELECT windowed_stats.ticker,
            windowed_stats.exchange_code,
            windowed_stats.date_epoch,
            windowed_stats.volume,
            windowed_stats.traded,
            windowed_stats.sum_volume_7d,
            windowed_stats.sum_volume_30d,
            windowed_stats.sum_traded_7d,
            windowed_stats.sum_traded_30d,
            windowed_stats.avg_traded_7d,
            windowed_stats.avg_traded_30d,
            windowed_stats.instant_vwap,
            (array_remove(array_agg(windowed_stats.instant_vwap) OVER (PARTITION BY windowed_stats.ticker, windowed_stats.exchange_code ORDER BY windowed_stats.date_epoch ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), NULL::numeric))[array_upper(array_remove(array_agg(windowed_stats.instant_vwap) OVER (PARTITION BY windowed_stats.ticker, windowed_stats.exchange_code ORDER BY windowed_stats.date_epoch ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), NULL::numeric), 1)] AS last_known_vwap
           FROM windowed_stats
        )
        SELECT row_number() OVER () AS id,
            ticker,
            exchange_code,
            date_epoch,
            to_timestamp((date_epoch / 1000)::double precision)::date AS calendar_date,
            traded AS traded_daily,
            COALESCE(instant_vwap, last_known_vwap, 0::numeric) AS vwap_daily,
            sum_traded_7d,
            COALESCE(avg_traded_7d, 0::numeric) AS avg_traded_7d,
            COALESCE(sum_volume_7d / NULLIF(sum_traded_7d, 0::numeric), last_known_vwap, 0::numeric) AS vwap_7d,
            sum_traded_30d,
            COALESCE(avg_traded_30d, 0::numeric) AS avg_traded_30d,
            COALESCE(sum_volume_30d / NULLIF(sum_traded_30d, 0::numeric), last_known_vwap, 0::numeric) AS vwap_30d
        FROM locf_logic
        WHERE date_epoch = (( SELECT constants.today_epoch
        FROM constants));

        CREATE UNIQUE INDEX idx_game_analytics_unique ON prunplanner_game_exchanges_analytics (ticker, exchange_code, date_epoch);
        CREATE INDEX idx_game_analytics_perf ON prunplanner_game_exchanges_analytics (ticker, exchange_code, date_epoch DESC);
        CLUSTER prunplanner_game_exchanges_analytics USING idx_game_analytics_unique;
    """)

def rollback_materialized_view(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return

    schema_editor.execute("DROP MATERIALIZED VIEW IF EXISTS prunplanner_game_exchanges_analytics;")
    schema_editor.execute("""
        CREATE MATERIALIZED VIEW prunplanner_game_exchanges_analytics AS
        WITH physical_exchanges AS (
            SELECT unnest(ARRAY['AI1'::text, 'IC1'::text, 'NC1'::text, 'CI1'::text])::character varying AS exchange_code
        ),
        ticker_scaffold AS (
            SELECT
                m.ticker,
                e.exchange_code,
                (EXTRACT(epoch FROM date_trunc('day'::text, now())) * 1000::numeric)::bigint AS date_epoch,
                0::numeric AS volume,
                0::numeric AS traded
            FROM prunplanner_game_materials m
            CROSS JOIN physical_exchanges e
        ),
        combined_source AS (
            SELECT
                ticker,
                exchange_code,
                date_epoch,
                volume::numeric AS volume,
                traded::numeric AS traded
            FROM prunplanner_game_exchanges_cxpc
            UNION ALL
            SELECT ticker, exchange_code, date_epoch, volume, traded
            FROM ticker_scaffold
        ),
        base_aggregated AS (
            SELECT
                combined_source.ticker,
                COALESCE(combined_source.exchange_code, 'UNIVERSE'::character varying) AS exchange_code,
                combined_source.date_epoch,
                sum(combined_source.volume) AS volume,
                sum(combined_source.traded) AS traded
            FROM combined_source
            GROUP BY GROUPING SETS (
                (combined_source.ticker, combined_source.exchange_code, combined_source.date_epoch),
                (combined_source.ticker, combined_source.date_epoch)
            )
        ),
        windowed_stats AS (
            SELECT
                ticker,
                exchange_code,
                date_epoch,
                volume,
                traded,
                sum(volume) OVER w7 AS sum_volume_7d,
                sum(volume) OVER w30 AS sum_volume_30d,
                sum(traded) OVER w7 AS sum_traded_7d,
                sum(traded) OVER w30 AS sum_traded_30d,
                avg(traded) OVER w7 AS avg_traded_7d,
                avg(traded) OVER w30 AS avg_traded_30d,
                -- Calculate price for this specific row IF data exists, else NULL
                CASE WHEN traded > 0 THEN volume / traded ELSE NULL END as instant_vwap
            FROM base_aggregated
            WINDOW
                w7 AS (PARTITION BY ticker, exchange_code ORDER BY date_epoch RANGE BETWEEN 518400000 PRECEDING AND CURRENT ROW),
                w30 AS (PARTITION BY ticker, exchange_code ORDER BY date_epoch RANGE BETWEEN 2505600000 PRECEDING AND CURRENT ROW)
        ),
        locf_logic AS (
            SELECT
                *,
                -- Find the last non-null instant_vwap looking backwards
                (array_remove(array_agg(instant_vwap) OVER (PARTITION BY ticker, exchange_code ORDER BY date_epoch ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), NULL))
                [array_upper(array_remove(array_agg(instant_vwap) OVER (PARTITION BY ticker, exchange_code ORDER BY date_epoch ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), NULL), 1)]
                AS last_known_vwap
            FROM windowed_stats
        )
        SELECT
            row_number() OVER () AS id,
            ticker,
            exchange_code,
            date_epoch,
            to_timestamp((date_epoch / 1000)::double precision)::date AS calendar_date,
            traded AS traded_daily,
            -- Daily fallback
            COALESCE(instant_vwap, last_known_vwap, 0::numeric) AS vwap_daily,
            sum_traded_7d,
            COALESCE(avg_traded_7d, 0::numeric) AS avg_traded_7d,
            -- 7d fallback
            COALESCE(sum_volume_7d / NULLIF(sum_traded_7d, 0::numeric), last_known_vwap, 0::numeric) AS vwap_7d,
            sum_traded_30d,
            COALESCE(avg_traded_30d, 0::numeric) AS avg_traded_30d,
            -- 30d fallback
            COALESCE(sum_volume_30d / NULLIF(sum_traded_30d, 0::numeric), last_known_vwap, 0::numeric) AS vwap_30d
        FROM locf_logic;

        CREATE UNIQUE INDEX idx_game_analytics_unique ON prunplanner_game_exchanges_analytics (ticker, exchange_code, date_epoch);
        CREATE INDEX idx_game_analytics_perf ON prunplanner_game_exchanges_analytics (ticker, exchange_code, date_epoch DESC);
        CLUSTER prunplanner_game_exchanges_analytics USING idx_game_analytics_unique;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0019_update_analytics_locf'),
    ]

    operations = [
        migrations.RunPython(update_materialized_view, reverse_code=rollback_materialized_view),
    ]
