# Generated by Django 6.0.8 on 2026-09-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0020_auto_20260320_1254'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gameexchangecxpc',
            name='idx_ticker_exchange',
        ),
    ]
