# Generated by Django 6.0.8 on 2026-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0021_remove_gameexchangecxpc_idx_ticker_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebuilding',
            name='expertise',
            field=models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('CHEMISTRY', 'Chemistry'), ('CONSTRUCTION', 'Construction'), ('ELECTRONICS', 'Electronics'), ('FOOD_INDUSTRIES', 'Food Industries'), ('MANUFACTURING', 'Manufacturing'), ('METALLURGY', 'Metallurgy'), ('RESOURCE_EXTRACTION', 'Resource Extraction'), ('FUEL_REFINING', 'Fuel Refining')], db_index=True, default=None, max_length=50, null=True),
        ),
    ]
