# Generated by Django 6.0.8 on 2026-09-27 11:24

from django.db import migrations

BLANK_TO_NULL_FIELDS = {
    'GameBuilding': ['expertise'],
    'GamePlanet': ['faction_code', 'faction_name', 'cogc_program_status'],
}


def blank_to_null(apps, schema_editor):
    for model_name, fields in BLANK_TO_NULL_FIELDS.items():
        model = apps.get_model('gamedata', model_name)
        for field in fields:
            model.objects.filter(**{field: ''}).update(**{field: None})


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0022_gamebuilding_expertise_default_none'),
    ]

    operations = [
        migrations.RunPython(blank_to_null, reverse_code=migrations.RunPython.noop),
    ]
