# Generated by Django 6.0.8 on 2026-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0023_blank_to_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefioplayerdata',
            name='fio_status_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(200, 'Data'), (204, 'No data yet'), (401, 'Key rejected')], null=True, verbose_name='FIO answer'),
        ),
    ]
