# Generated by Django 6.0.8 on 2026-10-01 12:39

from django.db import migrations


def backfill(apps, schema_editor):
    """Rows from before fio_status_code: without it every connected user would read as syncing until the next refresh."""
    GameFIOPlayerData = apps.get_model('gamedata', 'GameFIOPlayerData')
    rows = GameFIOPlayerData.objects.filter(fio_status_code__isnull=True)
    # last refresh succeeded
    rows.filter(automation_error_count=0).update(fio_status_code=200)
    # last refresh failed on a rejected key; str(httpx.HTTPStatusError) reads "Client error '401 Unauthorized' ..."
    rows.filter(automation_error__contains="'401 ").update(fio_status_code=401)


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0024_fio_status_code'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_code=migrations.RunPython.noop),
    ]
